feat(admin, notification)
Sul-Game-Wiki/Sul-Game-Backend pull request #10
Opened 2024-07-08 11:40 UTC by username056

2024-07-11 05:37 UTC, Cassiiopeia requested changes

2024-07-11 11:36 UTC, daye200 requested changes

2024-07-11 11:36 UTC, daye200 commented on src/main/java/org/sejong/sulgamewiki/admin/domain/entity/Admin.java
> +
email validation 로직은 있나요??

2024-07-11 11:36 UTC, daye200 commented on src/main/java/org/sejong/sulgamewiki/admin/domain/presentation/AdminController.java
> +}
한번 해봤어요

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/application/AdminService.java
> +
Admin List는 필요없을것같습니다.

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/application/AdminService.java
> +    public Admin updateAdmin(Long id, Admin adminDetails) {
adminDetails 이게뭐가요?? 
Admin으로 받으면안되죠

UpdateAdmin이면 이제 바꾸는 부분을 잘 생각해서 그부분을 DTO로 포장해서 받아야죠

저같으면 명명을 updateAdminRequest 라는 DTO를 하나 만들것같아요

이거 챗지피티한테 물어보면 명명 이름추천 많아요

종류가 많은데 Form이라는 표현도 씁니다. 뒤에 Dto 를 붙이기도합니다. 

Response랑 Request를 나눠서 생각해서 폴더를 제가 나눠놓긴했는데 

나누죠 일단 ㅎㅎ

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/application/AdminService.java
> +        admin.setId(adminDetails.getId());
Id는 변경하면 큰일나요~

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/application/AdminService.java
> +        return adminRepository.save(admin);
dTO로 바꿔서 리턴해주세요

updateAdminResponse 라는 객체 만들어서 

안에다가 public static from( Admin admin){
} 이렇게 메소드로 DTO로 바꾸는겁니다.

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/domain/entity/Admin.java
> +public class Admin extends BaseEntity {
만약 어떤 abstract class로 상속받는다고합시다 

근데 java는 다중 상속을 지원안해요

그래서

BaseUser 라고 만들었다고 치면 거기에서 BaseEntiy를 상속해야될꺼예요 

그리고 Builder 어노테이션도 한번 찾아봐야될것같아요 

이게 Builder가 속 안까지는 지원을 안할텐데

SuperBuilder인가 이런 어노테이션이있는데 이게 써야되는지 안써야되는지 확실하지는 않아요 

기억이 안납니다 한번 써보고 아래단에 있는거 builder로 못쓰면 안되는거니까 방법 찾아봐야해요

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/dto/AdminDto.java
> +@Builder
@Getter
@Setter 기본으로 넣어야해요

DB바뀌면 다시 짜야될것같아서 화이팅

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/notification/domain/entity/Notification.java
> +    @Enumerated(EnumType.STRING)
한번 뭐인지 찾아봅시다

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/notification/domain/entity/Notification.java
> +    @Enumerated(EnumType.STRING)
CommnetType.CREATIVE.toString() -> "CREATIVE"

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/notification/presentation/NotificationController.java
> +    private NotificationService notificationService;
!!

2024-07-11 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/notification/presentation/NotificationController.java
> +    @GetMapping("/members/{memberId}/notifications")
URL 이 흠... 
RequestMapping("/noti") 이런식으로 ??

한번 고민해봅시다 ㅎㅎ

2024-07-14 17:57 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/application/AdminService.java
> +
근데 이거 baseMember에서 하면 안되나?

2024-07-14 18:20 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/application/AdminService.java
> +        admin.setId(adminDetails.getId());
c

2024-07-14 18:20 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/application/AdminService.java
> +
c

2024-07-14 18:21 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/domain/entity/Admin.java
> +public class Admin extends BaseEntity {
c...?

2024-07-15 08:20 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/admin/dto/AdminDto.java
> +@Builder
c...?

2024-07-15 08:37 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/notification/presentation/NotificationController.java
> +    private NotificationService notificationService;
AllArgsConstructor로 수정

2024-07-15 11:26 UTC, merged