fix(Home): 홈 엔티티 수정 및 홈화면 로드 로직 수정
Sul-Game-Wiki/Sul-Game-Backend pull request #101
Opened 2024-09-09 13:38 UTC by Mr-Tongyoung

2024-09-09 14:51 UTC, username056 reviewed
리뷰끝 LGTM👍

2024-09-09 14:51 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/repository/BasePostRepository.java
> +  Slice<BasePost> findGames(Pageable pageable);
이거 위에 있던것들 하나로 통합해서 지운건가??

2024-09-09 14:51 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +    }
스위치문 쓰지 말랬는데 이건 괜찮은겨??

2024-09-09 14:51 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +        )).getContent();
바꾼거랑 차이점이 뭐야? 페이지 넘버랑 사이즈가 하드코딩 되어있지 않은거??

2024-09-10 06:20 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/repository/BasePostRepository.java
> +  Slice<BasePost> findGames(Pageable pageable);
ㅇㅇ 정렬정보는 Pageable객체에 담아서 넘기는식으로 수정함

2024-09-10 06:23 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +        )).getContent();
원래는 레포지토리에 있는 메서드에 쿼리문 직접 하드코딩해놨던거라서 findOfficialGamesByLikes를 하나의 정렬기준, 정렬방향으로 사용했어야했는데 이렇게 하면 그나마 덜 하드코딩하는 느낌. 그래도 하드코딩이긴 한데 생각해보니 Sort.by(Sort.Direction.DESC, "likes") 이 부분도 커맨드에서 꺼내오면 되겠다

2024-09-10 08:41 UTC, Cassiiopeia requested changes
굿굿

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/CommentService.java
>          .build();
여긴또 commnet 반환했네 

comment안에 위에 내용 다 포함되어잇는거알죠?

  .content(comment.getContent())
        .commentId(comment.getCommentId())
        .memberId(comment.getMember().getMemberId())
        
        위 내용들 comment 반환하면 다보여요

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/CommentService.java
> +
comment update하는거 할때 

수정됨으로 표시하는거있었지않았나요
isEdited였나 뭐있었던것같은데 ...


delete하면 member 경험치 떨어지고
memberInteraction 에서 총댓글수도 떨어짐

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +            Sort.by(Sort.Direction.DESC, "dailyScore")
이거 dailyScore  이런거 위에서 정의해둔거 사용안하나요??



SortBy.

  CREATION_DATE("createdDate", "생성날짜순"),
  LIKES("likes", "좋아요순"),
  VIEWS("views", "조회수순"),
  DAILY_SCORE("dailyScore", "오늘의 인기순"),
  WEEKLY_SCORE("weeklyScore", "금주의 인기순");
  
  이거 사용해야죠

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +    switch (command.getPostType()) {
스위치문 사용 금지

if로 처리해요

else사용금지 

else if 로 처리해요

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +    }
당연히 안되지용

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +  }
이거 만들어놨는데 위에서 왜안씁네까?

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/util/exception/ErrorCode.java
> +  ALREADY_LIKED(HttpStatus.BAD_REQUEST, "좋아요는 한번만 누를 수 있습니다."),
좋아요한번만 누를수있어요?

다시누르면 좋아요 취소가되는거아닌가요?

2024-09-10 08:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/LikeService.java
> +        .basePost(savedBasePost)
일단 전제적으로 

member 경험치랑 
memberInteraction 로직 추가해주세요 total개수 다뤄야함

2024-09-10 08:47 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/HomeController.java
> +  @PostMapping(value = "/get-homepage", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
ㅇㅈ

2024-09-10 08:50 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/HomeDto.java
> +  private boolean hasNext;
무한스크롤할때 필요한거.
슬라이스로 반환해주고 화면내리다가 마지막쯤에 이벤트리스너 작동시키는데 그때 이 필드값 확인한다네

2024-09-10 08:56 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/repository/BasePostRepository.java
> +  Slice<Intro> findIntros(Pageable pageable);
수정했음

2024-09-10 09:00 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/CommentService.java
> +
삭제하면 낮아져야 한다고 하지 않았나요? 줬던 점수 다시 뺐는거 아닌가요?

2024-09-10 09:02 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +            Sort.by(Sort.Direction.DESC, "dailyScore")
넵

2024-09-11 04:57 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/util/exception/ErrorCode.java
> +  ALREADY_LIKED(HttpStatus.BAD_REQUEST, "좋아요는 한번만 누를 수 있습니다."),
아 그렇게 할수가 있겠군요
프론트에서 좋아요랑 좋아요취소랑 다른 api로 요청받을 생각이었습네다. 수정할게요

2024-09-11 05:04 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/CommentService.java
>          .build();
ERROR 61795 --- [nio-8080-exec-1] o.s.s.u.e.GlobalExceptionHandler         : Type definition error: [simple type, class org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor]
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor]

커맨드객체 반환하면 업데이트 메서드에서 이 에러가 자꾸떠서 이렇게 구현해놨슴둥

2024-09-11 05:12 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/CommentService.java
>          .build();
근데 무슨 에러인지 완벽하게 이해해버렸음 수정할게

2024-09-11 05:14 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/CommentService.java
> +
isEdited는 있었는데 생각해보니 BaseTimeEntity에 이미 isUpdated가 있어서 그거 했음둥

2024-09-11 05:27 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/LikeService.java
> +        .basePost(savedBasePost)
추가할게요

2024-09-11 05:59 UTC, username056 reviewed
잘봣습니다~

2024-09-11 05:59 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/object/Comment.java
> +        }
이거 어차피 한번 더 하면 취소 아냐? 어떨 때 사용하려고 만든 예외처리야?

2024-09-11 05:59 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/object/constants/SortBy.java
> +public enum SortBy {
전체 인기순은?  처음부터 현재까지 이어지는 토탈은 여기서 없어도 되는겨?? 얘가 어디서 쓰이는지 아직 안봐서모르겟네요~

2024-09-11 05:59 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/object/constants/SourceType.java
> +  GAMES("게임(공식,창작 둘다 포함)"),  //공식게임과 창작게임 모두를 받아야할때 사용
이거 오늘 가장 핫했던 술게임 섹션에서 쓰는건가요?

2024-09-11 06:03 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/Comment.java
> +        }
어떨때 사용하려고 만든건 아니고 그냥 혹시몰라 예외처리긴한데... 나도 쓸데없을거라 생각해서 지우려했는데 그냥 남겨놨던거

2024-09-11 06:04 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/constants/SourceType.java
> +  GAMES("게임(공식,창작 둘다 포함)"),  //공식게임과 창작게임 모두를 받아야할때 사용
네 맞습니다

2024-09-11 06:04 UTC, Cassiiopeia requested changes
일단 급하니 중간에 한번 올렸습니다

2024-09-11 06:04 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> +  }
이거 잘생각해보면

프론트가 어떻게 차리할지 생각해보면

프론트는 좋아요를 누르기전에 

이미 뷰 화면에  내가 좋아요를 눌러놨으면

좋아요가 찍혀있겠죠???

빨간색으로??

그러면 프론트입장에서는 cancelLike 기능을 하는 api를 쏘는게 맞겠죠??
그리고 게시글 상세보기에서 값 보내줄때

한번 if(this.likedMemberIds.contains(memberId)){ 

이거 한번 돌려봐서

이용자가 이 게시글에 좋아요를 눌렀는지 안눌렀는지 알려주는 로직도 있어야겠네요

반환값에 

isMemberLiked() =true 값이 프론트한테가면

프론트는 좋아요를 클릭해져있는 상태로 view 보여주면되잖아요

2024-09-11 06:26 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/HomeController.java
> +    return ResponseEntity.ok(homeService.getPosts(command));
모든 포스트 입니다

프론트한테 어떤 SourceType인지 받아와서 해당하는 포스트 전체 가져오는거요

2024-09-11 06:56 UTC, Cassiiopeia requested changes
이런방향성으로가고 API명세를 잘해줍시다

2024-09-11 06:56 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/CommentController.java
> +    }
로직은 무조건 서비스단에서합시다

이거 두개로 나누는거 서비스단에서 분리해요

2024-09-11 06:56 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/HomeController.java
> +    return ResponseEntity.ok(homeService.getPosts(command));
> 모든 포스트 입니다
> 
> 프론트한테 어떤 SourceType인지 받아와서 해당하는 포스트 전체 가져오는거요

이해가 안가는데 해당하는 포스트 전체를 가져오는게 main에서 어느부분 클릭하면 그렇게 가져오는거예요??

2024-09-11 06:56 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/IntroController.java
> +    }
controller는 api요청부분을을 가져오는것만
Header값 건드리고 그런로직이 아니면

무조건 로직은 service에서해요

2024-09-11 06:56 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameController.java
> +      return ResponseEntity.ok(likeService.cancelPostLike(command));
여기도

2024-09-11 07:08 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/HomeController.java
> +    return ResponseEntity.ok(homeService.getPosts(command));
전체보기요

2024-09-11 09:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/HomeController.java
> +    return ResponseEntity.ok(homeService.getPosts(command));
전체보기를 home에서 처리하나요?

2024-09-11 09:31 UTC, Cassiiopeia requested changes

2024-09-11 09:31 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameController.java
> +  @PostMapping("/details")
뒤에 MULTIPART

2024-09-11 09:31 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> +    }
이거 set으로 하지말고

메소드로 접근해주세요

그리고 각각 memberInteracion과 member 에있는값 바꿔야해요

2024-09-11 09:31 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/Comment.java
> +        }
이것도 메서드로

2024-09-11 09:31 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/constants/ScoreRule.java
> +  DOWN_LIKE(10, "해당 게시글 좋아요를 취소하면 -10 포인트 부여"),
CANCEL

2024-09-11 09:36 UTC, merged