feat(comment): 서비스, 레포지토리, 엔티티 작성
Sul-Game-Wiki/Sul-Game-Backend pull request #11
Opened 2024-07-08 11:42 UTC by Mr-Tongyoung

2024-07-10 14:46 UTC, Cassiiopeia requested changes
허허 공부좀 합시다

너무 돌리고 바로 쓴 티가 나요

 제가원하는건 꼬리무는 질문으로 돌리는겁니다.

혼납니다?

2024-07-10 14:46 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/comment/application/CommentService.java
> +    }
저희가 언제 @Autowired를 썼죠??

@Autowired와 @RequiredArgsContructor 였나 이거 차이점 한번 공부한거 올려보셔요

@RequiredArgsContructor 이걸로 수정해주세요

2024-07-10 14:46 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/comment/application/CommentService.java
> +                .orElseThrow(() -> new RuntimeException("Game not found"));
RunTimeException보다 CustomExeption 상속해서 커스텀한 Exception으로 사용해주세요 
GameException extends CustomException 이렇게요 만드신거있죠??

제코드 보시면 무슨말인지 알것같아요

2024-07-10 14:46 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/common/entity/BaseComment.java
> +}
Base Comment라는 Abstract Class를  따로 만든 이유가 궁금하네요??

다른곳에서도 사용하는건가요??

2024-07-10 14:46 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/comment/domain/entity/Comment.java
> +    private PopularGame game;
흠~ PopularGame밖에 안보이네요 

저희는 Comment 종류가 좀 많은데 

어떤식으로 구현하실꺼죠??

그냥 Comment 에 CommentType 이런식으로 Enum Class를 연결해서
PopularGame , CreativeGame , Song 이런식으로 분류할수도있고 

애초에 3개의 Comment Table을 만들수도있구요

전체적으로 바꾸셔야할것같아요

2024-07-10 14:46 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/comment/presentation/CommentController.java
> +    }
Autowired 사용하지맙시다

2024-07-10 14:46 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/comment/presentation/CommentController.java
> +    }
RequestBody는 DTO로 받아야죠 Comment로 받는건아니예요

새로운 Dto Class만들어서 뭐 예를 들면

addCommentRequest 라는 class만들어서

사람들이 뭘 입력해야겠어요?? private String context 만있으면 될것같은데요??

그냥 텍스트만 입력하고 확인 누를것같은데 그죠?

그리고 gameId라고하면안돼요 왜냐하면 지금 제가 table 두개로 나눴잖아 popluarGame이랑 creativeGame 이거 두개로 나눴잖아요

그래서 gameid가 두개가 겹칠수가있어요

그러니까 api 를 두개로 쪼개던지 아니면 파라미터값을 어떤게임type인지 받을수도있구요 

알아서 구현하시면될듯

2024-07-14 04:04 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/common/entity/BaseComment.java
> +}
BaseGame 과 BaseMedia가 BaseEntity 상속받고 하길래 entity짤때는 그런건가보다 하고 별 생각없이 했는데....
생각해보니 댓글은 댓글내용, 작성일자, 작성자id, 댓글 고유id 이렇게만 있으면 되겠네요. 수정하겠습니다

2024-07-15 11:27 UTC, merged