홈서비스 구현 및 인트로 생성
Sul-Game-Wiki/Sul-Game-Backend pull request #47
Opened 2024-08-25 14:48 UTC by Mr-Tongyoung

2024-08-25 23:26 UTC, Cassiiopeia requested changes

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +@Transactional
이거 service단위에 쓰는거 아님

뭔지 찾아봅시다 매우 중요한 어노테이션임

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
>      List<CreationGame> latestCreationGameList = latestCreativeGamesSlice.getContent();
이거한줄로 합칠수있는거아니요?

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
>      List<Intro> introsListByLikes = introsSliceByLikes.getContent();
한줄로 핮치고 introsList는 같은 의미가 두번담김

intros로 통일합시다

introsSliceByLikes 라는 변수는 필요없는듯

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
>      Slice<Intro> introsByViews = basePostRepository.findByViews(pageable);
findByView 변수이름 바꿔야될듯요

이것만보면 view 뭘 찾아오는건지 모르겠네요

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +    Slice<BasePost> postsSliceByDailyScore = basePostRepository.findPostsByWeeklyScore(pageable);
기억이 안나는데 WeeklyScore에서도 좋아요 조회수 댓글순으로 나누나요?

그러면 메소드이름도 세분화되어야함

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +        .latestIntroList(latestIntrosList)
우리 List는 s 붙입시다

통일하는게좋음

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> -    // HomeDto에 담아서 반환
지금 변수들이 통일성이 안맞는것같음

위에서는 creationGameDailyChart
아래에서는 weeklyHotGames??

전체적으로. List와 s를 혼동해서 쓰고있고

형용사가 앞에 나오는지 그리고 위에서는 chart라는 표현쓰고 아래는 그냥 왜 games라는표현??

아 그리고 이거 왜그냥 games죠?

2024-08-25 23:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/IntroService.java
이거보니까 왜 소영이가 mediaService 필요하다고 하는지 알겠군

ㅇㅈ합니다 

S3Service안에 넣는것보다
BaseMedia 엔티티를 지금 3개의 부분에서 사용하니까

MediaService로 빼서 관리하는게 맞겠네

만약 S3 Seevice에서 사용하면
안에 무조건 BaseMediaRepository가있는데
그럼 S3관련된 서비스에서 꼭... BaseMedia레포 의존성을 가져야되나 생각이듬

기능분리를 위해 

이 로직이 계속 쓰일텐데
MediaService로 따로 나누는게좋을듯

2024-08-26 03:27 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +    Slice<BasePost> postsSliceByDailyScore = basePostRepository.findPostsByWeeklyScore(pageable);
나누는거 아니고 좋아요 3점 조회 1점 댓글 1점 뭐 이런식으로 총점수 따져서 하는거 아니었나요?

2024-08-26 03:34 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
>      List<Intro> introsListByLikes = introsSliceByLikes.getContent();
슬라이스 지금은 필요없는데 어떤 게시판에 대해서 전체보기 클릭했을때 넘겨줘야할거같아서 저렇게 해놨는데 있어야하지 않을까?

2024-08-26 04:26 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
>      List<Intro> introsListByLikes = introsSliceByLikes.getContent();
> 슬라이스 지금은 필요없는데 어떤 게시판에 대해서 전체보기 클릭했을때 넘겨줘야할거같아서 저렇게 해놨는데 있어야하지 않을까?

 List<Intro> introsByLikes = basePostRepository.findIntrosByLikes(pageable).getContent();
 
 이거 한줄로 쓰면되지않나요

2024-08-26 04:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> +    Slice<BasePost> postsSliceByDailyScore = basePostRepository.findPostsByWeeklyScore(pageable);
> 나누는거 아니고 좋아요 3점 조회 1점 댓글 1점 뭐 이런식으로 총점수 따져서 하는거 아니었나요?

맞네맞네

2024-08-26 05:54 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
>      List<Intro> introsListByLikes = introsSliceByLikes.getContent();
그래도 슬라이스가 되나?
리스트 변수에 담아놓은거에는 슬라이스 성질 안들어가있을거 아니야
내가 말한건 전체보기 눌렀을때는 basePostRepository.findIntrosByLikes(pageable) 이걸 넘겨줘야하는거 아니냐는거지.
지금 저 리스트는 그냥 홈화면에서 게시판당 5개 보여주는거에 쓰라고 던져준거고

2024-08-26 06:10 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
>      Slice<Intro> introsByViews = basePostRepository.findByViews(pageable);
그러네요 findIntrosByViews로 수정할게요

2024-08-26 06:17 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/HomeService.java
> -    // HomeDto에 담아서 반환
통일시킬게요
그냥 games인 이유는 인트로 제외하고 (공식, 창작)술게임이라서 저렇게 씀 allGames로 할까?

2024-08-26 06:43 UTC, Cassiiopeia approved these changes

2024-08-26 06:43 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/IntroController.java
> +    return ResponseEntity.ok(introDto);
이것도 완전한 한줄로 가능하긴함 ㅋㅋ

2024-08-26 06:43 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/IntroCommand.java
> +  @Builder.Default
이게 들어가면 위에서

Controller단에서 
        .multipartFiles(multipartFiles != null ? multipartFiles : new ArrayList<>())
        .build();
        
        이거 필요없어요

2024-08-26 06:43 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/repository/BasePostRepository.java
>    @Query("SELECT p FROM CreationGame p WHERE p.isDeleted = false ORDER BY p.dailyScore DESC")
이거 p나 b나 변수이름에 정해진 규칙이 있나요?

아니면 하나로 합칩시다

2024-08-26 06:51 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/IntroCommand.java
> +  @Builder.Default
!= null ? multipartFiles : new ArrayList<>()
이 부분이 필요없다는거죠?

2024-08-26 07:02 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/IntroController.java
> +    return ResponseEntity.ok(introDto);
이거 한줄은 어떻게...?

2024-08-26 07:17 UTC, merged