feat(report): 신고 로직 적용 및 수정
Sul-Game-Wiki/Sul-Game-Backend pull request #52
Opened 2024-08-29 10:36 UTC by username056

2024-08-29 16:06 UTC, Mr-Tongyoung requested changes
훌륭하네요

2024-08-29 16:06 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/ReportService.java
> +    BasePost basePost = basePostRepository.findById(reportCommand.getSourceId())
getSourceId -> getBasePostId 이게 낫지 않나?  Source는 지금 게시글 종류 구분할때 쓰고있는데 좀 헷갈리는듯? 개인적인 의견

2024-08-29 16:06 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/ReportService.java
> +        .sourceId(basePost.getBasePostId())
여기도 보면 통일성 떨어지는듯

2024-08-29 16:07 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +
주석처리된 부분들은 뭔가요? 지울건가요?

2024-08-29 16:09 UTC, Cassiiopeia requested changes
오호 좋아요 ~

2024-08-29 16:10 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/CreationGame.java
> +  private String introLyrics;
> 나 이 부분 좀 헷갈리는데. OfficialGame이랑 CreationGame에 들어가는 인트로는 우리가 만든 객체 Intro가 아니고 그냥 가사랑 미디어파일 하나만 있게 되는거인거야?
> 
> 아님 이것도 객체를 만들어서 OfficialGame이랑 CreationGame에 넣게되는건가?

노노 객체 만드는게 아니라 애초에 intro가 따로있는게 아니라 아예 포함되는거

2024-08-29 16:13 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> +  private SourceType sourceType;
좀 찾아봤는데 그냥 ENUM파일 하나 만드는게 수월할듯 dtype가져오려면 괜히 쿼리문 하나 날려야하네

2024-08-29 16:15 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/CreationGame.java
> +  private String introLyrics;
아예 포함된다는게 OfficialGame안에 Intro객체가 포함된다는게 아니지?
그냥 가사랑 미디어파일 필드 넣는다는거지?

2024-08-29 23:47 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/CreationGame.java
> +  private String introLyrics;
> 아예 포함된다는게 OfficialGame안에 Intro객체가 포함된다는게 아니지? 그냥 가사랑 미디어파일 필드 넣는다는거지?

맞소맞소

2024-08-29 23:49 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/ReportService.java
> +    BasePost basePost = basePostRepository.findById(reportCommand.getSourceId())
> getSourceId -> getBasePostId 이게 낫지 않나? Source는 지금 게시글 종류 구분할때 쓰고있는데 좀 헷갈리는듯? 개인적인 의견

그렇게 쓰면 좋겠지만 

Report가 comment인지 basePost 기준인지 몰라서

어쩔수없이 sourceId로 하자고 했던 기억이 있음

2024-08-29 23:51 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/ReportService.java
> +        .orElseThrow(() -> new CustomException(ErrorCode.COMMENT_NOT_FOUND));
여기보면 getSourceId() 가 comment id로도 쓰여서 그럼
@Mr-Tongyoung 

그래서 이름이 sourceId인데 다른 방법 좋은거있음 추천좀 ㅋㅋ

2024-08-30 06:29 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +
지우는 거 깜빡했다 지웠습니다~

2024-08-30 06:46 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/service/ReportService.java
> +    BasePost basePost = basePostRepository.findById(reportCommand.getSourceId())
게시글 종류 구분할 때 쓰는 걸 PostType으로 수정하는건 어떰?

2024-08-30 08:43 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/object/CreationGame.java
> +  private String introLyrics;
근데 나 어제 이해를 못해서 미디어 파일 필드는 빼놨었는데 대신 넣어주실 분 없나요😅😅

2024-08-30 11:06 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/ReportService.java
> +    BasePost basePost = basePostRepository.findById(reportCommand.getSourceId())
소영이말이 맞는듯 포스트타입 ㄱㄱ

2024-08-30 11:14 UTC, Cassiiopeia approved these changes

2024-08-30 11:14 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/CreationGameService.java
> +    command.setBasePost((savedCreationGame));
이거괄호두개 해도괜찮아?

2024-08-30 11:17 UTC, merged