미디어서비스 및 s3서비스 업데이트,삭제 로직
Sul-Game-Wiki/Sul-Game-Backend pull request #55
Opened 2024-08-30 14:03 UTC by Mr-Tongyoung

[Merge remote-tracking branch 
이 커밋은 빼고 보세요... 왜 이렇게 됐는지 모르겠는데 새찬이가 올렸던 pr내용이 그대로 커밋이됐네....

2024-08-31 03:41 UTC, Cassiiopeia requested changes
굿

2024-08-31 03:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/constants/Tag.java
> +}
description에 들어가야되고

이름을 따로

2024-08-31 03:41 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePostCommand.java
> +//  private List<MultipartFile> introMultipartFiles;
각각 따로 해야해

2024-09-01 13:17 UTC, Cassiiopeia requested changes
이거 예전코드같은데 고친코드 안올라온것같은데?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/IntroController.java
> +  }
굿굿 주석지웁시다

잘 작동하나요?? Put은 나도 잘 안쓰는 방식이라서

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/IntroControllerDocs.java
> +        - **`Object<Icon>`**: 인트로에 대한 아이콘
Object??

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/IntroControllerDocs.java
> +          _선택 사항_
이거 어떻게 처리하나요??

List<sTring> 기존이미지url
과

List<MultipartFile> 새로 업로드된 파일 

이렇게 두개로 받는걸로했나요? 물어봄?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> +  private String thumbnailIcon;
@Column(length = 255) 이거 굳이 있어야하나요?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePostCommand.java
> +  private Boolean isPrivate = false;
무슨오류?
Command에 오류가 왜생기죠??

Command에 왜 기본값이 있죠?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePostCommand.java
> +  private List<MultipartFile> introMultipartFiles;
무슨오류?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePostDto.java
> +  private Map<Long, List<BaseMedia>> baseMediaMap;
Map사용하는것으로했나요?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/Intro.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
public으로 둘꺼면 
@NoArgsConstructor 으로 두면될듯

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/constants/IntroTag.java
> +
물어봤나요? 정빈인한테?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/repository/BaseMediaRepository.java
> +  @Query("SELECT entity.mediaUrl FROM BaseMedia entity WHERE entity.basePost.basePostId = :basePostId AND entity.isDeleted = false")
BaseMedia는 그냥 삭제한다고했지않음??

isDeleted칼럼이 의미가있나요?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/repository/BasePostRepository.java
>    BasePost findByBasePostId(Long relatedOfficialGameId);
BasePost findByBasePostId(Long basePostId);

라는 표현이 적덜한것같아요

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/repository/BasePostRepository.java
>    List<BasePost> findByBasePostIdIn(List<Long> ids);
@Query("SELECT entity FROM BasePost entity WHERE entity.basePostId IN :ids AND entity.isDeleted = false")
  List<BasePost> findByBasePostIdIn(List<Long> ids);

이것도

이게 효율적인지

그냥 for문 돌려서  List<BasePost> findByBasePostId(List basePostIds);

이게 더 효율적인지 

뭐가다른건지 확인하고 써야할것같아요

물론 지금방식과 다른방식이 있나 궁금하긴함

JPA가 어떤식으로 조회하는지 궁금해서

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +          iterator.remove(); // 안전하게 리스트에서 해당 URL 제거
여기에서도 Iterator 썼네 

이거 바꾸는거아니였나요?

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
이거그때 deleteFile 안에서 따로 try catch문써서 밖으로 Exception Throw 안해야되지않나요

try catch 문 뺴도 잘 작동되어야할텐데 

예전에 봤던 코드로 봤을때는

2024-09-01 13:17 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/IntroService.java
> +    Intro intro = (Intro) basePostRepository.findByBasePostId(basePostId);
Intro안에 값 다 들어오는지 확인해야함

어 이거 Optional해서 이전에 다 바꾼거아니엿나

2024-09-01 14:03 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/IntroControllerDocs.java
> +          _선택 사항_
다예랑 얘기했음. 그렇게 두개 받기로 함ㅇㅇ

2024-09-01 14:04 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/IntroControllerDocs.java
> +        - **`Object<Icon>`**: 인트로에 대한 아이콘
뭐가될지 몰라서 임시로 저렇게 써놓음

2024-09-01 18:10 UTC, Cassiiopeia requested changes
모든 api 정상 작동하는지 테스트 해야해

2024-09-01 18:10 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/IntroController.java
> +  @PostMapping("/details")
MediaType.MULTIPART_FORM_DATA_VALUE)

2024-09-01 18:16 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> +  private String thumbnailIcon;
나중에 썸네일아이콘 만들어지면 수정하는걸로 하시죠.... 뇌에 과부하가 왔습니다

2024-09-01 18:17 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/BasePostCommand.java
> +  private Boolean isPrivate = false;
없앴습니다. basePost에서 꺼내오면 될거같은데 어떻게 생각하시나요

2024-09-02 05:18 UTC, username056 reviewed
LGTM👍

2024-09-02 05:18 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/object/constants/GameTag.java
> +}
태그 수정하기로 했는데 아직 안한거야? 아니면 한국어로 해놔도 괜찮은거??

2024-09-02 05:37 UTC, Cassiiopeia requested changes

2024-09-02 05:37 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/constants/GameTag.java
> +}
이거 태그 id값으로 바꿉시다

1 2 3 4 5 6 7 8 9 이런식으로 바꾸고 

description에 저 값 넣어요

2024-09-02 05:37 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +          throw new RuntimeException(e); //TODO: change error
@username056  안고쳤나용~?

2024-09-02 05:37 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +        : command.getGameMultipartFiles();
음... 저같으면 쉽게  if 랑 else-if 로 바꾸고 같긴한데 

이런 조건문 if 와 else같은경우 else안쓰는거랑 비슷한 논리긴해요

가독성도 고려하면... 제 취향임

2024-09-02 05:37 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +      }
이거 왜있는 로직이죠?

2024-09-02 05:37 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/ScoreResetService.java
> +  @Scheduled(cron = "0 0 0 1/1 * ? *")
이건 비동기적으로 작동해야하는 작업이라

비동기적으로 작동하게 변경해주세요

2024-09-02 05:37 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/ScoreResetService.java
> +  @Scheduled(cron = "0 0 0 ? * SUN *")
이건 비동기적으로 작동해야하는 작업이라

비동기적으로 작동하게 변경해주세요

이거 지울동안 다른작업못하면안되잖아요

2024-09-02 06:04 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +      }
이거 새찬씨가 만든 로직입니다

2024-09-02 06:14 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +          throw new RuntimeException(e); //TODO: change error
내가 고침

2024-09-02 06:16 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/constants/GameTag.java
> +}
이성과하기좋아요(1, "이성과 하기 좋아요"),
    빨리취해요(2, "빨리 취해요"),
    움직여야해요(3, "움직여야 해요"),
    머리를써야해요(4, "머리를 써야 해요"),
    스킨쉽있어요(5, "스킨쉽 있어요"),
    엄청빨라요(6, "엄청 빨라요"),
    차분해요(7, "차분해요"),
    금방끝나요(8, "금방 끝나요"),
    오래걸려요(9, "오래 걸려요"),
    눈치챙겨(10, "눈치 챙겨"),
    센스가필요해요(11, "센스가 필요해요"),
    도구가필요해요(12, "도구가 필요해요"),
    저격할수있어요(13, "저격할 수 있어요"),
    텐션올릴때좋아요(14, "텐션 올릴 때 좋아요");

이렇게??

2024-09-02 06:17 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/IntroController.java
> +  @PostMapping("/details")
이거는 GetMapping 아닌가?

2024-09-02 11:28 UTC, merged