feat(officialGame): CRUD 구현
Sul-Game-Wiki/Sul-Game-Backend pull request #71
Opened 2024-09-04 10:36 UTC by username056

2024-09-04 11:03 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameController.java
>    public ResponseEntity<BasePostDto> getPopularGame(
이름 바꾸세요 언제적 포퓰러에요~

2024-09-04 11:12 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/CreationGameService.java
> +            .creatorInfoIsPrivate(command.getCreatorInfoIsPrivate())
이거 메서드 만든거 넣어서 잘 해주세요

2024-09-04 11:12 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +    existingOfficialGame.setCreatorInfoIsPrivate(command.getCreatorInfoIsPrivate());
여기도 메서드 써주시고

2024-09-05 01:27 UTC, Cassiiopeia requested changes
이거 Intro 어떻게 관리함?

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameController.java
> +  @PutMapping(name = "/update", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
Post

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameController.java
> +  @DeleteMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
POST

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameControllerDocs.java
> +          - **`Object<Icon>`**: 게임에 대한 아이콘
Object? Icon??

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameControllerDocs.java
> +          - **`Boolean creatorInfoIsPrivate`** null값 불가능
이거 변수이름 바꿉시다 

저희 Boolean값 is로 시작하게 통일합시다

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameControllerDocs.java
>            - **`List<BaseMedia> baseMedias`**: 게임과 연관된 미디어 파일 리스트
이거 인트로 미디어  파일 주소랑

게임 미디어 파일주소랑 구분안하나요??

애초에 OfficialGame안에 IntroMediaUrl 이 들어가있나요?

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameControllerDocs.java
>    )
업데이트 필요 

예전 주석

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/controller/OfficialGameControllerDocs.java
> +  )
이것도 입력파라미터값 postId랑 jwt토큰 필요함

MemberControllerDocs 확인해주고 그방식대로 주석수정 해주세요

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> + }
이거 왜 orElse가 true임??

이거 값 아무것도안오면 공개여야하는거 아님?

그리고 메소드명이랑 안에 로직이 안맞음

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/OfficialGame.java
> -
OfficialGame에 없음??

이거 각각에 인트로 미디어 인트로가사 들어가는거아니였음??

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/CreationGameService.java
> +            .isUpdated(false)
사소한건데 이런 부수적인 설정값들은 아래로 내리는게 내취향

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/CreationGameService.java
> +            .creatorInfoIsPrivate(command.getCreatorInfoIsPrivate())
이 메소드는 다른곳에서 안쓰이고 

command와 관련된 구조같은데

다른곳에서 쓰일려면 

OfficialGame 안에 들어갈 메소드가 아니라 따로 util 쪽에서 global하게 쓰이도록 따로 관리해야할것같은데

애초에 관리자 게임만드는건데 왜 private 이 필요해요 ㅋㅋ

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> + }
isCreatorInfoPrivateOrDefault ???

뭐이런식으로 해야할것같은데 

그리고 Boolean info 도 변수이름 맘에안듬 무슨 info인데?

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/IntroService.java
>        throw new CustomException(ErrorCode.GAME_NOT_FOUND); // 예외를 발생시킴
이것도 지워야죠? 위에서 예외처리했으니까

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/IntroService.java
>        throw new CustomException(ErrorCode.GAME_NOT_FOUND); // 예외를 발생시킴
이것도지워야죠?

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +
왜지웠죠? 이게뭔지 알고지운거??

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +            .isUpdated(false)
저같으면 이거 피그마에 정의한순으로 일단 input값부터 놓고 설정값 따로 아래에 적겠음 

순서 가독성 문제

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +  public BasePostDto updateOfficialGame(BasePostCommand command) {
위에 Transactional 추가

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +    existingOfficialGame.setThumbnailIcon(command.getThumbnailIcon());
업데이트할께 이거밖에없음?

그리고 애초에 인트로는 따로하기로함?

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +    // 게시글과 미디어 파일 저장
주석이 위로 가야될것같음

게시물 저장 및 미디어 파일 업데이트(저장)

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
Transactional

2024-09-05 01:27 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +    officialGame.markAsDeleted();
이미지는 삭제안하나요??

굳이 가지고있을필요있을까요?

2024-09-05 04:50 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/service/CreationGameService.java
> +            .creatorInfoIsPrivate(command.getCreatorInfoIsPrivate())
basePost에 있는 필드라서 거기에 static으로 만들었는데  util로 뺄까요? 그리고 관리자 게임이니까 private 필요 없다는 건 동의< 어떤 값이 들어오든(값이 애초에 안들어오는게 맞지만) 무조건 공개로 설정해두겠습니다

2024-09-05 05:03 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +
어우 클날뻔했네요 다시 공부하고 추가했습니다~

2024-09-05 06:20 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +            .isCreatorInfoPrivate(checkCreatorInfoIsPrivate(command.getCreatorInfoIsPrivate()))
getCreatorInfoIsPrivate -> getIsCreatorInfoPrivate 변경해줘용

2024-09-05 11:39 UTC, merged