feat(basePost): 게임인트로미디어관련 수정
Sul-Game-Wiki/Sul-Game-Backend pull request #80
Opened 2024-09-05 15:07 UTC by username056

2024-09-06 05:23 UTC, Cassiiopeia requested changes
지금 일단 Token도입되면 Docs도 다 바꿔야되고

그리고 Controller단 다 Post요청으로 바꿔주고 

겹치는  Url 도 변경해야겠죠??

그리고 무조건 modelAttribute으로 command 랑 userdetails랑
받아오는거

단순조회는 보안 안걸려있어야하고

WebConfig에도 각각 api좌표 추가도해야죠

이거 접근을 못해요

일반적인 조회주소는 화이트리스트 등록도해야되고

2024-09-06 05:23 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePostCommand.java
> +  private String introMediaFileInGamePostUrl;
흠흠 변수이름이....여긴 IN이고 아래는 FROM이고

그리고 introMediaFileInGamePostUrl 흠... 

지금 BasePost에 IntroMediaUrl 이라고되어있나요?? 뭐라고 설정되어있죠??

만약 BasePost에 String IntroMediaUrl  라고 설정되어있다면

IntroMediaUrlFromGame 이라고할것같음

2024-09-06 05:23 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePostDto.java
> +  private BaseMedia introMediaFromGame;
일관성무엇 ㅋㅋㅋ

introMediaFromGame ㅇㅋㅇㅋ

2024-09-06 05:23 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/BasePostDto.java
> +  private BaseMedia introMediaFileInGamePost;
introMediaFileInGamePost

!ㅇㅋㅇㅋ

isSucks(introMediaFileInGamePost) == true

나같으면 introMediaFromGame 이라고 하던지 일단 고민해보죠?

2024-09-06 05:23 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/object/CreationGame.java
> +  private String introMediaFileInGamePostUrl;
여긴 다 in인데 

introMediaFileInGamePostUrl 

이게 문법상

introMediaUrlInGame 

이 맞지않나?

from in 하나로 통일하고

Url이 왜 뒤에있는지 모르겠음요

 introMediaUrl 이라고해도되고

2024-09-06 05:33 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/object/BasePostDto.java
> +  private BaseMedia introMediaFileInGamePost;
개발자식 돌려까기 무엇ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-09-07 10:32 UTC, Cassiiopeia approved these changes

2024-09-07 10:32 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> + //       .baseMedias(updatedIntroMediaFromGame)
이거왜 주석?

2024-09-07 10:32 UTC, Cassiiopeia commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +
나같으면 이렇게도 나쁘지않겠지만 BaseMediaService로 뺴는것도 고쳐는 해볼것가타요

2024-09-16 03:11 UTC, Mr-Tongyoung requested changes
스웨거에서 값 넣어보고 작동되는것만 잘 확인했으면 주석좀 지우고 머지하면 될거같아요

2024-09-16 03:11 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +  public BaseMedia updateIntroMediaFromGame(BasePostCommand command) {
아 이거는 게임게시물에서 인트로 미디어 1개씩 넣는거 관련 메서드지??

2024-09-16 03:11 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +  public BaseMedia updateIntroMediaFromGame(BasePostCommand command) {
잘 작동하는거 확인했어??

2024-09-16 03:11 UTC, Mr-Tongyoung commented on src/main/java/org/sejong/sulgamewiki/service/OfficialGameService.java
> +    //TODO: 해당 포스트와 연관된 창작 술게임 가져와야함
얘도 지워주숑

2024-09-16 13:34 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/repository/BasePostRepository.java
> +  List<CreationGame> findCreationGamesByRelatedOfficialGame(OfficialGame officialGame);
걔네의 RelatedOfficialGame을 통해 찾는거라 저게 더 명확하지 않나? 사실 거기서 거기인 것 같기는 해

2024-09-16 13:40 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/service/BaseMediaService.java
> +  public BaseMedia updateIntroMediaFromGame(BasePostCommand command) {
officialGame에서 업데이트 메서드로 추가하고 삭제되는거 확인했어 잘 작동함

2024-09-16 13:46 UTC, username056 commented on src/main/java/org/sejong/sulgamewiki/object/BasePost.java
> +  @Size(max = 20, message = "제목 20자 제한")
하나는 데베 레벨에서 막는거고 하나는 사용자 입력에서 막는 거라 둘이 다르긴 한데... 걍 더 안전하게 가게 넣은거라... 일단 머지할테니까 맘에 안들면 오빠가 삭제해바

2024-09-16 13:46 UTC, merged